export type ErrorCode = 'INVALID_URL' |
	'INVALID_PROTOCOL' |
	'NO_HUB' |
	'UNSUPPORTED_WEBSOCKET' |
	'UNAUTHORIZED' |
	'CONNECTION_LOST' |
	'ERR_NEGOTIATE' |
	'ERR_CONNECT' |
	'ERR_START' |
	'ERR_SOCKET' |
	'ERR_ABORT';
